# Generated by Django 4.2.7 on 2023-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.IntegerField(default=0),
        ),
    ]
